# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  ServerName: 'appdbsrv'
  ## DatabaseName: '<Database name>'
  AdminUser: 'adam'
  AdminPassword: 'I like azure.' ## Don't do this
  SQLFile: 'new_sql_database.sql'

steps:
- task: CmdLine@1
  displayName: Run Sqlcmd
  inputs:
    filename: Sqlcmd
    ## arguments: '-S $(ServerName) -U $(AdminUser) -P $(AdminPassword) -d $(DatabaseName) -i $(SQLFile)'
		arguments: '-S $(ServerName) -U $(AdminUser) -P $(AdminPassword) -i $(SQLFile)'
